appname: task


server:
  port: 88
  servlet:
    context-path: /${appname}
  tomcat:
    accept-count: 100
    max-threads: 600

mybase:
  task:
    tenant: {1: test_loandb,2: test2_loandb}

spring:
  application:
    name: ${appname}
  datasource:
    url: jdbc:mysql://rds.finchinfo.cn:3306/test_loandb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: test
    password: ENC(zudg3PTIEsW//PqJOkVaOUVLTirIR7li)
  jpa:
    show-sql: true
    open-in-view: false

jasypt:
  encryptor:
    password: qwer1234tyu

#log
logging:
  level:
    root: info
    cn:
      strivers: debug

